name = "cgpcal"
description = "calculate cgpa"
version = "0.0.1"
terminal = false
packages = [
    "/static/wheels/cgpcal-0.0.1-py3-none-any.whl",
    "/static/wheels/toga_core-0.4.5-py3-none-any.whl",
    "/static/wheels/toga_web-0.4.5-py3-none-any.whl",
    "/static/wheels/travertino-0.3.0-py3-none-any.whl",
]

[splashscreen]
autoclose = true
